<?php
$data = array (
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '果汁饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '果汁饮料',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '乳品',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '乳品',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '咖啡饮料',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '水',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '水',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '苏打',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '苏打',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '碳酸饮料',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '果汁',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '植物蛋白饮料',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '植物蛋白饮料',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '功能饮料',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '茶饮料',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '休闲食品',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '蜜饯',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '4',
    'name' => '蜜饯',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '鱼干',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '鱼干',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '枣类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => '枣类',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '即食肉类',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '5',
    'name' => '即食肉类',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '薯片',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '果冻',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '果冻',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '小食',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '小食',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '坚果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '3',
    'name' => '坚果',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '海苔',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '海苔',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '膨化',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '膨化',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '洗浴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '65',
    'name' => '洗浴用品',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '洗手液',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '68',
    'name' => '洗手液',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '澡巾',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '澡巾',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '花露水',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '69',
    'name' => '花露水',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '66',
    'name' => '沐浴露',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '浴盐',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '70',
    'name' => '浴盐',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '67',
    'name' => '香皂',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '浴球浴花',
    'measure_unit' => '',
    'parent_id' => '65',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '浴球浴花',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '早餐食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '30',
    'name' => '早餐食品',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '火腿肠',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '火腿肠',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '牛奶',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '牛奶',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '面包',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '78',
    'name' => '女性护理',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '暖贴',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '84',
    'name' => '暖贴',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '夜用卫生巾',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '81',
    'name' => '夜用卫生巾',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '洗液',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '85',
    'name' => '洗液',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '护垫',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '82',
    'name' => '护垫',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '卫生巾',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '79',
    'name' => '卫生巾',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '组合套装',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '83',
    'name' => '组合套装',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '日用卫生巾',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '日用卫生巾',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '59',
    'name' => '洗发护发',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '洗护套装',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '洗护套装',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '定型造型',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => '定型造型',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '洗发水',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => '电吹风',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '护发润发',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '护发润发',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '方便食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '34',
    'name' => '方便食品',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '方便粉丝',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '方便粉丝',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '肉罐头',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '肉罐头',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '火腿肠',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '火腿肠',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '水产罐头',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '水产罐头',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '八宝粥',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '八宝粥',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '方便面',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '方便面',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '水果罐头',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '水果罐头',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '数码配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '114',
    'name' => '数码配件',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '鼠标',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '116',
    'name' => '鼠标',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '清洁用品',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '123',
    'name' => '清洁用品',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '摄像头',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '120',
    'name' => '摄像头',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '键盘',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '117',
    'name' => '键盘',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '其他数码配件',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '124',
    'name' => '其他数码配件',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '网线',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '121',
    'name' => '网线',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '存储卡',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '118',
    'name' => '存储卡',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '耳机耳麦',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '115',
    'name' => '耳机耳麦',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '数据线',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '122',
    'name' => '数据线',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '读卡器',
    'measure_unit' => '',
    'parent_id' => '114',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '119',
    'name' => '读卡器',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '饼干蛋糕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '饼干蛋糕',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '面包',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '14',
    'name' => '饼干',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '蛋糕',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '蛋糕',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '15',
    'name' => '曲奇',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '点心',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '点心',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '蛋卷',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '蛋卷',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '威化',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '威化',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '73',
    'name' => '口腔护理',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '73',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '75',
    'name' => '牙刷',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '漱口水',
    'measure_unit' => '',
    'parent_id' => '73',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '76',
    'name' => '漱口水',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '牙签',
    'measure_unit' => '',
    'parent_id' => '73',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '77',
    'name' => '牙签',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '73',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '74',
    'name' => '牙膏',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '家居日用',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '105',
    'name' => '家居日用',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '保暖贴',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '保暖贴',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '晾衣架',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '晾衣架',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '107',
    'name' => '毛巾',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '收纳篮',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '收纳篮',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '浴巾',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '108',
    'name' => '浴巾',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '口罩',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '口罩',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '洗衣袋',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '109',
    'name' => '洗衣袋',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '106',
    'name' => '拖鞋',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '男性护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '86',
    'name' => '男性护理',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '男士护理套装',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '男士护理套装',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '剃须护理',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '89',
    'name' => '剃须护理',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '男士面部护理',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '87',
    'name' => '男士面部护理',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '96',
    'name' => '衣物清洁',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '100',
    'name' => '洗衣皂',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '衣领净',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '衣领净',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '去渍剂',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '104',
    'name' => '去渍剂',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '衣物护理',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '101',
    'name' => '衣物护理',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '98',
    'name' => '洗衣液',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '衣物除菌',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '102',
    'name' => '衣物除菌',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '99',
    'name' => '洗衣粉',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '彩漂',
    'measure_unit' => '',
    'parent_id' => '96',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '103',
    'name' => '彩漂',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '面部护肤',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '16',
    'goods_num' => 0,
    'level' => 0,
    'id' => '42',
    'name' => '面部护肤',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '美白',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '美白',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '眼部保养',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '眼部保养',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '面霜',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '面膜',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '防晒',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '保湿',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '保湿',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '精华',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => '精华',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '乳液',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '乳液',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '洁面',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '抗皱',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '抗皱',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '控油',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '控油',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '润唇膏',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '润唇膏',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '护肤套装',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '护肤套装',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '爽肤水',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '卸妆',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '卸妆',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '祛痘',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '祛痘',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '纸制品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '90',
    'name' => '纸制品',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '软包抽纸',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '94',
    'name' => '软包抽纸',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '盒纸',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '91',
    'name' => '盒纸',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '卷筒纸',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => '卷筒纸',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '手帕纸',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '手帕纸',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '湿纸巾',
    'measure_unit' => '',
    'parent_id' => '90',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '93',
    'name' => '湿纸巾',
  ),
);
?>